USE ANS_DB_P3
TRUNCATE TABLE AFSTEMNING
TRUNCATE TABLE LOGGING
TRUNCATE TABLE HEALTH_REPORT
TRUNCATE TABLE MANAGER_TRACKING
TRUNCATE TABLE ENGINE_PROPERTIES
TRUNCATE TABLE LOGGING_CONTEXT
TRUNCATE TABLE MANAGERS